#!/bin/bash

if [ `whoami` != 'root' ]
then
    echo "Launch it as root"
    exit 1
fi

if [ $# -eq 1 -a $# -eq 2 ]
NM=`uname -a && date`
NAME=`echo $NM | md5sum | cut -f1 -d" "`
then
	ppa_name=`echo "$1" | cut -d":" -f2 -s`
	if [ -z "$ppa_name" ]
	then
		echo "PPA name not found"
		echo "Utility to add PPA repositories in your debian machine"
		echo "$0 ppa:user/ppa-name [ubuntu version]"
	else
		echo "$ppa_name"
		if [ $# -eq 1 ]
		then
			echo "deb http://ppa.launchpad.net/$ppa_name/ubuntu xenial main" >> /etc/apt/sources.list
		else
			echo "deb http://ppa.launchpad.net/$ppa_name/ubuntu $2 main" >> /etc/apt/sources.list
		fi
		apt update >> /dev/null 2> /tmp/${NAME}_apt_add_key.txt
		if grep NO_PUBKEY /tmp/${NAME}_apt_add_key.txt
		then
			echo "Public key to add :"
			cat /tmp/${NAME}_apt_add_key.txt | grep NO_PUBKEY | sed -E "s/^.*NO_PUBKEY (.+)$/\1/" | xargs -i echo "- " {}
			cat /tmp/${NAME}_apt_add_key.txt | grep NO_PUBKEY | sed -E "s/^.*NO_PUBKEY (.+)$/\1/" | xargs -i apt-key adv --keyserver keyserver.ubuntu.com --recv-key {}
		else
			echo "No public key to add"
		fi
		rm -rf /tmp/${NAME}_apt_add_key.txt
	fi
else
	echo "Utility to add PPA repositories in your debian machine"
	echo "$0 ppa:user/ppa-name [ubuntu version]"
fi

