#!/bin/bash

is_repo ()
{
	if [ $(cut -d ' ' -f 1 <<< "$1") = "deb" ]
	then
		return 0
	else
		return 1
	fi
}

display_help ()
{
	echo "Utility to add PPA and repositories in your debian machine"
        echo "$0 ppa:user/ppa-name [ubuntu version]"
	echo "or"
	echo "$0 deb repo-url branch section1 [other-section]"
	echo
	echo "$0 update to update the tool to the lastest version"
}

if [ `whoami` != 'root' ]
then
	echo "Launch it as root"
	exit 1
fi

NM=`uname -a && date`
NAME=`echo $NM | md5sum | cut -f1 -d" "`

if [ $# -ge 1 ] && [ $1 = "update" ]
then
	curl_dir=`whereis -b curl`
	wget_dir=`whereis -b wget`
	diff_dir=`whereis -b diff`

	if [ "$diff_dir" = "diff:" ]
	then
		echo "You need diffutils to use updater"
		exit 1
	fi

	if [ "$curl_dir" = "curl:" ]
	then
		if [ "$wget_dir" = "wget:" ]
		then
			echo "You need wget or curl to use updater"
			exit 1
		else
			wget -q "https://raw.githubusercontent.com/Cadichon/Debian_PPA/master/add-apt-repository" -O /tmp/${NAME}
		fi
	else
		curl -s "https://raw.githubusercontent.com/Cadichon/Debian_PPA/master/add-apt-repository" > /tmp/${NAME}
	fi

	if !(diff /usr/bin/add-apt-repository /tmp/${NAME} &> /dev/null)
	then
		echo "Updating..."
		rm /usr/bin/add-apt-repository
		cp /tmp/${NAME} /usr/bin/add-apt-repository
		chmod +x /usr/bin/add-apt-repository
	else
		echo "Already Up-to-date"
	fi
	rm /tmp/${NAME}
	exit 0
fi

if [ $# -ge 1 ]
then
	if is_repo "$1"
	then
		count=1
		while [ $count -le $# ]
		do
			echo -n "${!count} " >> /etc/apt/sources.list
			(( count++ ))
		done
		exit 0
	fi
	ppa_name=`echo "$1" | cut -d":" -f2 -s`
	if [ -z "$ppa_name" ]
	then
		echo "PPA name not found"
		display_help
	else
		echo "$ppa_name"
		if [ $# -eq 1 ]
		then
			echo "deb http://ppa.launchpad.net/$ppa_name/ubuntu xenial main" >> /etc/apt/sources.list
		else
			echo "deb http://ppa.launchpad.net/$ppa_name/ubuntu $2 main" >> /etc/apt/sources.list
		fi
		apt update >> /dev/null 2> /tmp/${NAME}_apt_add_key.txt
		if grep -q NO_PUBKEY /tmp/${NAME}_apt_add_key.txt
		then
			echo "Public key to add :"
			cat /tmp/${NAME}_apt_add_key.txt | grep NO_PUBKEY | sed -E "s/^.*NO_PUBKEY (.+)$/\1/" | xargs -i echo "- " {}
			cat /tmp/${NAME}_apt_add_key.txt | grep NO_PUBKEY | sed -E "s/^.*NO_PUBKEY (.+)$/\1/" | xargs -i apt-key adv --keyserver keyserver.ubuntu.com --recv-key {}
		else
			echo "No public key to add"
		fi
		rm -rf /tmp/${NAME}_apt_add_key.txt
	fi
else
	display_help
fi
